## René Parlange, MSc
### 📚 Machine Learning Course, PhD in Computer Science
#### 🎓 Instructor: Juan Carlos Cuevas Tello, PhD
#### 🏛 Universidad Autónoma de San Luis Potosí (UASLP)

🔗 [GitHub Repository](https://github.com/parlange)

# Autoencoder, Tensorflow and Keras

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
import time

# Define the input pattern
Pattern = np.array([[1, 1, 0, 0, 0, 0],
                    [0, 0, 1, 1, 0, 0],
                    [0, 0, 0, 0, 1, 1]])

start_time = time.time()

Inputs = 6  # Number of input variables
TrainData = Pattern[:, :Inputs]
TestData = TrainData

# Create an autoencoder model
input_layer = Input(shape=(Inputs,))
encoded = Dense(8, activation='relu')(input_layer)  # Encoder
decoded = Dense(Inputs, activation='sigmoid')(encoded)  # Decoder

autoencoder = Model(input_layer, decoded)

# Compile the autoencoder
autoencoder.compile(optimizer='adam', loss='mse')

# Training stage
print("Training...")
autoencoder.fit(TrainData, TrainData, epochs=1000, verbose=0)

# Testing stage
print("Testing...")
reconstructed_data = autoencoder.predict(TestData)

print(reconstructed_data.round())

# Check if the data matches
match = (TrainData == reconstructed_data.round()).all()
print("\nMatch:", match)

# Print the execution time
end_time = time.time()
print("\nExecution time:", end_time - start_time, "seconds")

Training...
Testing...
1/1 [==============================] - 0s 49ms/step
[[1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1.]]

Match: True

Execution time: 4.745255470275879 seconds
