## René Parlange, MSc
### 📚 Machine Learning Course, PhD in Computer Science
#### 🎓 Instructor: Juan Carlos Cuevas Tello, PhD
#### 🏛 Universidad Autónoma de San Luis Potosí (UASLP)

🔗 [GitHub Repository](https://github.com/parlange)

# Autokeras image classification
### Documentation
[autokeras_image_classification](https://autokeras.com/tutorial/image_classification/)

In [ ]:
!pip install autokeras

  Using cached autokeras-1.1.0-py3-none-any.whl (148 kB)
  Using cached keras_tuner-1.4.4-py3-none-any.whl (127 kB)
  Using cached keras_nlp-0.6.2-py3-none-any.whl (590 kB)
  Using cached keras_core-0.1.7-py3-none-any.whl (950 kB)
  Using cached tensorflow_text-2.14.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.5 MB)
  Using cached kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
  Using cached namex-0.0.7-py3-none-any.whl (5.8 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 489.8/489.8 MB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 69.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 10.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 109.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 43.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 90.5 MB/s eta 0:00:00
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.1

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist

import autokeras as ak

Using TensorFlow backend


## A Simple Example
The first step is to prepare your data. Here we use the MNIST dataset as an example


In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)  # (60000, 28, 28)
print(y_train.shape)  # (60000,)
print(y_train[:3])  # array([7, 2, 1], dtype=uint8)

11490434/11490434 [==============================] - 0s 0us/step
(60000, 28, 28)
(60000,)
[5 0 4]


The second step is to run the ImageClassifier.
It is recommended have more trials for more complicated datasets.
This is just a quick demo of MNIST, so we set max_trials to 1.
For the same reason, we set epochs to 10.
You can also leave the epochs unspecified for an adaptive number of epochs.


In [ ]:
# Initialize the image classifier.
clf = ak.ImageClassifier(overwrite=True, max_trials=1)
# Feed the image classifier with training data.
clf.fit(x_train, y_train, epochs=10)


# Predict with the best model.
predicted_y = clf.predict(x_test)
print(predicted_y)


# Evaluate the best model with testing data.
print(clf.evaluate(x_test, y_test))

Trial 1 Complete [00h 01m 28s]
val_loss: 0.04008492827415466

Best val_loss So Far: 0.04008492827415466
Total elapsed time: 00h 01m 28s
Epoch 1/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1626 - accuracy: 0.9499
Epoch 2/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0740 - accuracy: 0.9777
Epoch 3/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0597 - accuracy: 0.9814
Epoch 4/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0508 - accuracy: 0.9837
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0447 - accuracy: 0.9858
Epoch 6/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0419 - accuracy: 0.9869
Epoch 7/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0375 - accuracy: 0.9882
Epoch 8/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0351 - accuracy: 0.9882
Epoch 9/10
1875/1875 [==========================

## Validation Data
By default, AutoKeras use the last 20% of training data as validation data. As
shown in the example below, you can use validation_split to specify the
percentage.


In [ ]:
clf.fit(
    x_train,
    y_train,
    # Split the training data and use the last 15% as validation data.
    validation_split=0.15,
    epochs=10,
)

You can also use your own validation set instead of splitting it from the
training data with validation_data.


In [ ]:
split = 50000
x_val = x_train[split:]
y_val = y_train[split:]
x_train = x_train[:split]
y_train = y_train[:split]
clf.fit(
    x_train,
    y_train,
    # Use your own validation set.
    validation_data=(x_val, y_val),
    epochs=10,
)

## Customized Search Space
For advanced users, you may customize your search space by using AutoModel
instead of ImageClassifier. You can configure the ImageBlock for some
high-level configurations, e.g., block_type for the type of neural network to
search, normalize for whether to do data normalization, augment for whether to
do data augmentation. You can also do not specify these arguments, which would
leave the different choices to be tuned automatically. See the following
example for detail.


In [ ]:
input_node = ak.ImageInput()
output_node = ak.ImageBlock(
    # Only search ResNet architectures.
    block_type="resnet",
    # Normalize the dataset.
    normalize=True,
    # Do not do data augmentation.
    augment=False,
)(input_node)
output_node = ak.ClassificationHead()(output_node)
clf = ak.AutoModel(
    inputs=input_node, outputs=output_node, overwrite=True, max_trials=1
)
clf.fit(x_train, y_train, epochs=10)

Trial 1 Complete [00h 10m 07s]
val_loss: 0.1556057631969452

Best val_loss So Far: 0.1556057631969452
Total elapsed time: 00h 10m 07s
Epoch 1/10
1563/1563 [==============================] - 94s 43ms/step - loss: 0.3559 - accuracy: 0.9138
Epoch 2/10
1563/1563 [==============================] - 66s 42ms/step - loss: 0.2915 - accuracy: 0.9369
Epoch 3/10
1563/1563 [==============================] - 66s 42ms/step - loss: 0.1302 - accuracy: 0.9669
Epoch 4/10
1563/1563 [==============================] - 66s 42ms/step - loss: 0.1487 - accuracy: 0.9673
Epoch 5/10
1563/1563 [==============================] - 67s 43ms/step - loss: 0.1724 - accuracy: 0.9595
Epoch 6/10
1563/1563 [==============================] - 66s 43ms/step - loss: 0.1281 - accuracy: 0.9675
Epoch 7/10
1563/1563 [==============================] - 66s 42ms/step - loss: 0.0874 - accuracy: 0.9757
Epoch 8/10
1563/1563 [==============================] - 66s 42ms/step - loss: 0.0528 - accuracy: 0.9850
Epoch 9/10
1563/1563 [============

The usage of AutoModel is similar to the functional API of Keras. Basically, you are
building a graph, whose edges are blocks and the nodes are intermediate outputs of
blocks. To add an edge from input_node to output_node with output_node =
ak.[some_block]([block_args])(input_node).

You can even also use more fine grained blocks to customize the search space even
further. See the following example.


In [ ]:
input_node = ak.ImageInput()
output_node = ak.Normalization()(input_node)
output_node = ak.ImageAugmentation(horizontal_flip=False)(output_node)
output_node = ak.ResNetBlock(version="v2")(output_node)
output_node = ak.ClassificationHead()(output_node)
clf = ak.AutoModel(
    inputs=input_node, outputs=output_node, overwrite=True, max_trials=1
)
clf.fit(x_train, y_train, epochs=10)

Trial 1 Complete [00h 09m 08s]
val_loss: 0.07368549704551697

Best val_loss So Far: 0.07368549704551697
Total elapsed time: 00h 09m 08s
Epoch 1/10
1563/1563 [==============================] - 84s 39ms/step - loss: 0.3684 - accuracy: 0.8977
Epoch 2/10
1563/1563 [==============================] - 60s 38ms/step - loss: 0.1577 - accuracy: 0.9553
Epoch 3/10
1563/1563 [==============================] - 59s 38ms/step - loss: 0.1493 - accuracy: 0.9596
Epoch 4/10
1563/1563 [==============================] - 60s 38ms/step - loss: 0.1142 - accuracy: 0.9673
Epoch 5/10
1563/1563 [==============================] - 59s 38ms/step - loss: 0.1312 - accuracy: 0.9653
Epoch 6/10
1563/1563 [==============================] - 59s 38ms/step - loss: 0.0951 - accuracy: 0.9724
Epoch 7/10
1563/1563 [==============================] - 59s 38ms/step - loss: 0.0786 - accuracy: 0.9774
Epoch 8/10
1563/1563 [==============================] - 59s 38ms/step - loss: 0.0674 - accuracy: 0.9805
Epoch 9/10
1563/1563 [==========

## Data Format
The AutoKeras ImageClassifier is quite flexible for the data format.

For the image, it accepts data formats both with and without the channel
dimension. The images in the MNIST dataset do not have the channel dimension.
Each image is a matrix with shape (28, 28). AutoKeras also accepts images of
three dimensions with the channel dimension at last, e.g., (32, 32, 3), (28,
28, 1).

For the classification labels, AutoKeras accepts both plain labels, i.e.
strings or integers, and one-hot encoded encoded labels, i.e. vectors of 0s and
1s.

So if you prepare your data in the following way, the ImageClassifier should
still work.


In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Reshape the images to have the channel dimension.
x_train = x_train.reshape(x_train.shape + (1,))
x_test = x_test.reshape(x_test.shape + (1,))

# One-hot encode the labels.
eye = np.eye(10)
y_train = eye[y_train]
y_test = eye[y_test]

print(x_train.shape)  # (60000, 28, 28, 1)
print(y_train.shape)  # (60000, 10)
print(y_train[:3])
# array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

(60000, 28, 28, 1)
(60000, 10)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


We also support using tf.data.Dataset format for the training data.


In [ ]:
train_set = tf.data.Dataset.from_tensor_slices(((x_train,), (y_train,)))
test_set = tf.data.Dataset.from_tensor_slices(((x_test,), (y_test,)))

clf = ak.ImageClassifier(overwrite=True, max_trials=1)
# Feed the tensorflow Dataset to the classifier.
clf.fit(train_set, epochs=10)
# Predict with the best model.
predicted_y = clf.predict(test_set)
# Evaluate the best model with testing data.
print(clf.evaluate(test_set))

Trial 1 Complete [00h 01m 24s]
val_loss: 0.039568863809108734

Best val_loss So Far: 0.039568863809108734
Total elapsed time: 00h 01m 24s
Epoch 1/10
1875/1875 [==============================] - 9s 4ms/step - loss: 0.1613 - accuracy: 0.9514
Epoch 2/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0753 - accuracy: 0.9768
Epoch 3/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0580 - accuracy: 0.9819
Epoch 4/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0502 - accuracy: 0.9839
Epoch 5/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0468 - accuracy: 0.9851
Epoch 6/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0415 - accuracy: 0.9865
Epoch 7/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0379 - accuracy: 0.9881
Epoch 8/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0355 - accuracy: 0.9883
Epoch 9/10
1875/1875 [========================

## Reference
[ImageClassifier](/image_classifier),
[AutoModel](/auto_model/#automodel-class),
[ImageBlock](/block/#imageblock-class),
[Normalization](/block/#normalization-class),
[ImageAugmentation](/block/#image-augmentation-class),
[ResNetBlock](/block/#resnetblock-class),
[ImageInput](/node/#imageinput-class),
[ClassificationHead](/block/#classificationhead-class).
