# René Parlange, MSc
### 📚 Machine Learning Course, PhD in Computer Science
#### 🎓 Instructor: Juan Carlos Cuevas Tello, PhD
#### 🏛 Universidad Autónoma de San Luis Potosí (UASLP)

🔗 [GitHub Repository](https://github.com/parlange)

## Bernoulli-Bernoulli Restricted Boltzmann Machines using scikit-learn

In [ ]:
import numpy as np
from sklearn.neural_network import BernoulliRBM
import time

# Data Preparation
Pattern = np.array([[1, 1, 0, 0, 0, 0],
                    [0, 0, 1, 1, 0, 0],
                    [0, 0, 0, 0, 1, 1]])
TrainData = Pattern

start_time = time.time()

# Train RBM
rbm = BernoulliRBM(n_components=3, learning_rate=0.05, batch_size=3, n_iter=2000, verbose=0)
rbm.fit(TrainData)

def reconstruct_from_hidden(hidden, rbm):
    #Reconstruct visible layer from hidden activations
    p = 1.0 / (1 + np.exp(-np.dot(hidden, rbm.components_) - rbm.intercept_visible_))
    return (p > 0.5).astype(int)

hidden_data = rbm.transform(TrainData)
reconstructed_data = reconstruct_from_hidden(hidden_data, rbm)

end_time = time.time()

print("Original Data:")
print(TrainData)

print("\nReconstructed Data:")
print(reconstructed_data)

match = (TrainData == reconstructed_data).all()
print("\nMatch:", match)

# Print the execution time
print("\nExecution time:", end_time - start_time, "seconds")

Original Data:
[[1 1 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 1 1]]

Reconstructed Data:
[[1 1 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 1 1]]

Match: True

Execution time: 0.12646007537841797 seconds
